version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: ro-devtest
    restart: always
    environment:
      POSTGRES_DB: rodevtest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devtest-api
    ports:
      - "5087:7014"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=rodevtest;Username=postgres;Password=root

volumes:
  pgdata:
